export const codeOfConduct = {
    title: "Code of Conduct",
    intro: "GDG is committed to providing a harassment-free and inclusive event experience for everyone, regardless of gender identity and expression, sexual orientation, disability, physical appearance, body size, race, nationality, age, religion, or other protected category. We do not tolerate harassment of participants in any form. GDG is committed to providing a harassment-free and inclusive event experience for everyone...",
    policyTitle: "All participants of GDG Taiwan events must adhere to the following policies:",
    policy1: "All participants should respect each other. We hope this event is a great experience for everyone, regardless of gender identity and expression, sexual orientation, disability, physical appearance, body size, race, nationality, age, religion, or other protected category. Respect everyone. When participating in an event, acknowledge that everyone has the right to be here and everyone has the right to enjoy our experience without worrying about harassment, discrimination, or disrespect, whether obvious or subtle. Jokes should not belittle others. Consider what you say, and if someone says or talks to you, what might they feel.",
    policy2: "If you see or hear something, speak up. Do not tolerate harassment. You have the right to intervene politely when someone is being harassed, whether it's yourself or someone else. The person who is making you uncomfortable may not realize they are doing something wrong, so encourage them to be polite. If a participant participates in harassment or unwelcome behavior, event organizers can take any action they deem appropriate, including warning or not refunding the offender from the event. If you are being harassed, or feel uncomfortable, notice that others are being harassed, or have any other questions, please contact the event staff immediately.",
    policy3: "Do not tolerate harassment. Harassment includes but is not limited to: reinforcing gender identity and expression, sexual orientation, disability, physical appearance, body size, race, nationality, age, religion, or other protected group's social structure's verbal language; sexual imagery in public spaces; intentional intimidation; following; recording or photographing harassment; persistent disruption of talks or other events; rude verbal language; inappropriate physical contact; and unwelcome sexual attention. Participants expected to immediately comply with requests to stop any harassment behavior.",
    policy4: "Practice saying 'Yes (your idea)…, and (my idea)…'. This is a theatrical improvisation technique to build ideas together. When we practice it together, we both benefit.",
    content1: "This policy applies to speakers, forums, workshops, code labs, social media, parties, hallway conversations, all participants, partners, sponsors, volunteers, and event staff. GDG Taiwan reserves the right to reject anyone from participating in any GDG Taiwan event (and future events). This includes but is not limited to, participants engaging in unacceptable behavior or failing to comply with this policy and related terms. If a participant engages in harassment or unwelcome behavior, event organizers can take any action they deem appropriate, including warning or not refunding the offender from the event.",
    content2: "Our event staff can usually be identified by special badges/clothing. Our zero-tolerance policy means we will investigate and review every complaint against our event community guidelines and harassment policies, and respond appropriately. Please note, although we take every complaint seriously, we will determine when and how to follow up on reported incidents based on our own judgment, and may not take any further action, and/or direct participants to other resources to resolve.",
    content3: "Event staff are happy to help participants contact hotel/venue security or local law enforcement, provide escorts, or otherwise assist those who feel uncomfortable or harassed during the event. We value your attendance.",
    contactList: {
      title: "If your personal safety or the safety of others is threatened, please call 110 immediately.",
      item1: "Code of Conduct Team: GDG Taiwan",
      item2: "Organizer: GDG Taiwan",
      item3: "Sexual Harassment Prevention Hotline of the Ministry of Health and Welfare (24 hours) : 113",
    },
    exhibitorPolicy: "This policy applies to speakers, forums, workshops, code labs, social media, parties, hallway conversations, all participants, partners, sponsors, volunteers, and event staff. GDG Taiwan reserves the right to reject anyone from participating in any GDG Taiwan event (and future events). This includes but is not limited to, participants engaging in unacceptable behavior or failing to comply with this policy and related terms. If a participant engages in harassment or unwelcome behavior, event organizers can take any action they deem appropriate, including warning or not refunding the offender from the event.",
    partners: {
      title: "Partners and Sponsors",
      description: "Exhibitors and sponsors also fall under this policy. Specifically, exhibitors should not use sexualized images, activities, or materials. Booth staff (including volunteers) should not use sexualized clothing/uniforms/costumes, or otherwise create a sexualized environment. Participants and exhibitors partners or sponsors who violate this policy will be notified and expected to immediately stop any violations.",
    },
    importance: { 
      title: "Why is this policy important?",
      description: "Unfortunately, harassment is common in events and online communities. By creating a formal policy, we aim to improve this situation, clearly stating that we do not accept harassment based on any reason in our events and communities. This policy can prevent harassment by clearly defining behavior expectations, providing assurance, and encouraging people who have had bad experiences in other events to participate in this event.",
    },
    license: {
      title: "License and Release",
      description: "This policy is licensed under the Creative Commons Zero license. This policy is based on and influenced by multiple other community policies, including: Ohio LinuxFest anti-harassment policy, Con anti-harassment project, Geek Feminism Wiki (created by Ada Initiative), ConfCodeofConduct.com, JSconf, Rust, Diversity in Python, and Write / Speak / Code.",
    },    
  };